version: '3.8'

services:
  beyondfire-cloud-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beyondfire-cloud-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_USERNAME=${PORTAINER_USERNAME}
      - PORTAINER_PASSWORD=${PORTAINER_PASSWORD}
      # - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      # - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_IP=${SERVER_IP}
    volumes:
      - beyondfire-logs:/app/logs
      - beyondfire-data:/app/data

  beyondfire-cloud-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: beyondfire-cloud-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - beyondfire-cloud-api

volumes:
  beyondfire-logs:
  beyondfire-data:
